"""Create schema

Revision ID: 0c5441b7def9
Revises:
Create Date: 2025-05-18 19:29:49.919758

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c5441b7def9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flamechart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("upload_uuid", sa.UUID(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("from_date", sa.DateTime(), nullable=False),
        sa.Column("to_date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flamechart_created_at"),
        "flamechart",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flamechart_filename"),
        "flamechart",
        ["filename"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flamechart_from_date"),
        "flamechart",
        ["from_date"],
        unique=False,
    )
    op.create_index(op.f("ix_flamechart_id"), "flamechart", ["id"], unique=False)
    op.create_index(
        op.f("ix_flamechart_prefix"),
        "flamechart",
        ["prefix"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flamechart_to_date"),
        "flamechart",
        ["to_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flamechart_upload_uuid"),
        "flamechart",
        ["upload_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flamechart_upload_uuid"), table_name="flamechart")
    op.drop_index(op.f("ix_flamechart_to_date"), table_name="flamechart")
    op.drop_index(op.f("ix_flamechart_prefix"), table_name="flamechart")
    op.drop_index(op.f("ix_flamechart_id"), table_name="flamechart")
    op.drop_index(op.f("ix_flamechart_from_date"), table_name="flamechart")
    op.drop_index(op.f("ix_flamechart_filename"), table_name="flamechart")
    op.drop_index(op.f("ix_flamechart_created_at"), table_name="flamechart")
    op.drop_table("flamechart")
    # ### end Alembic commands ###
