"""Add environment column

Revision ID: 6a53757853f1
Revises: 0c5441b7def9
Create Date: 2025-05-22 21:05:04.990877

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6a53757853f1"
down_revision = "0c5441b7def9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flamechart", sa.Column("environment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flamechart", "environment")
    # ### end Alembic commands ###
